version: '3.8'

services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
      - ./initial-db.sql:/docker-entrypoint-initdb.d/initial-db.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb_container

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
      - ./data/product-images:/var/www/html/wp-content/uploads
      - ./data/sample-products.csv:/var/www/html/wp-content/uploads/sample-products.csv
    container_name: wordpress_container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/wp-admin/install.php"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
  wordpress_data:
